### PR TITLE
added .idea to .gitignore

### LINKED ISSUE #1: add git ignore of .idea folders
add git ignore to remove .idea folders

### PR DESCRIPTION
**Pull request by Fetrixx**

### CODE REVIEW

**Comment by wendersonj** [comment]
Thanks for your contribution.

**Comment by wendersonj** [comment]
@Fetrixx was a good first issue ? Yesterday I was not being able to find proper good first issue for begginers. That said I create my own first issues haha

**Comment by wendersonj** [comment]
I can add that would be a good idea to complement the PR with the removal of the folder .idea

**Comment by Fetrixx** [comment]
Yeah, it was good first issue.

**Pull request merged**
